# This cloudbuild file is used by GitHub integration dev trigger.
steps:
# 0. Set the gcloud environment
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', '${_GCP_CONTAINER_CLUSTER}', '--zone=${_GCP_COMPUTE_ZONE}', '--project=${_PROJECT_ID}']

# 1. Lint the main docker file. Ignore DL3018 which enforces specifying Alpine package versions
- name: 'hadolint/hadolint'
  entrypoint: 'hadolint'
  args: ['Dockerfile', '--ignore', 'DL3018']

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  env:
  - '_SERVICE_NAME=${_SERVICE_NAME}'
  args:
  - '-c'
  - sed "s/COMMIT_SHA/${SHORT_SHA}/g" deployment-template.yaml > deployment.yaml
  - sed "s/SERVICE_NAME/_SERVICE_NAME/g" deployment-template.yaml > deployment.yaml

# 2. Build the application inside docker. Finally, build the image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '.']

# # 3. Tag the new image with latest so it can be pushed to GCR
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['tag', '${_SERVICE_NAME}:latest', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']

# 4. Deploy the application to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']

# 5. Deploy to kubernetes
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f' , 'deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_GCP_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GCP_CONTAINER_CLUSTER}'

substitutions:
  _PROJECT_ID: alfred-dev-1
  _SERVICE_NAME: alfred-gcp-support
  _GCP_COMPUTE_ZONE: asia-southeast1-a
  _GCP_CONTAINER_CLUSTER: alfred-dev-cluster-sg
