import os

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET")
SLACK_VERIFICATION_TOKEN = os.getenv("SLACK_VERIFICATION_TOKEN")
# PROJECT_ID =
# DATA_BACKEND = 
# CLOUD_STORAGE_BUCKET = 
# GOOGLE_OAUTH2_CLIENT_ID =
# GOOGLE_OAUTH2_CLIENT_SECRET =