import os

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET")
SLACK_VERIFICATION_TOKEN = os.getenv("SLACK_VERIFICATION_TOKEN")
PROJECT_ID = "alfred-dev-1"
# DATA_BACKEND = 
CLOUD_STORAGE_BUCKET = "alfred-uploaded-images"
# GOOGLE_OAUTH2_CLIENT_ID =
# GOOGLE_OAUTH2_CLIENT_SECRET =