apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: SERVICE_NAME
    spec:
      containers:
      - env:
        - name: SLACK_VERIFICATION_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SLACK_VERIFICATION_TOKEN
              name: SERVICE_NAME-config
        - name: SLACK_BOT_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SLACK_BOT_TOKEN
              name: SERVICE_NAME-config
        image: eu.gcr.io/alfred-dev-1/alfred-gcp-support:COMMIT_SHA
        imagePullPolicy: IfNotPresent
        name: github-jasonquekavalon-avalonx-slackbot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
