apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
  creationTimestamp: 2019-06-24T07:44:08Z
  generation: 30
  labels:
    app: alfred
  name: alfred
  namespace: default
  resourceVersion: "1584308"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/alfred
  uid: d94577f7-9653-11e9-af04-42010a9c0117
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alfred
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alfred
    spec:
      containers:
      - env:
        - name: SLACK_VERIFICATION_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SLACK_VERIFICATION_TOKEN
              name: alfred-config
        - name: SLACK_BOT_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SLACK_BOT_TOKEN
              name: alfred-config
        image: eu.gcr.io/alfred-dev-1/alfred-gcp-support:latest
        imagePullPolicy: IfNotPresent
        name: github-jasonquekavalon-avalonx-slackbot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-06-25T06:37:24Z
    lastUpdateTime: 2019-06-25T06:37:24Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 30
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
